More import cleanups that made cross-imports a mess
Over time I've come around on type hints, but modules that import each
other while also containing module-level code that the other module
uses make them difficult. You easily end up with both modules partially
imported and trying to use objects in their type hints or function
signatures that haven't been defined yet. This leads to errors like

    "AttributeError: module 'app_constants' has no attribute 'THUMB_H_SIZE'"

because an import of an import of app_constants already tries to use a
value from app_constants in a function signature before the interpreter
even got back to the part of app_constants where that attribute is
defined.

The only module now where global setup code is allowed is app_constants.
It turns out every other module was mostly fine except for utils. Its
formerly global code is now an init_utils() method that gets called as
soon as all imports in app are done.

I fixed up all affected function signatures that caused an error
startup. Unused imports are also removed.